server:
  port: 8761

spring:
  application:
    name: discovery-service
  jpa:
    enabled: false
  datasource:
    url: ""
    username: ""
    password: ""

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
