server:
  port: 8082

app:
  init:
    dev-dataset: true

spring:
  application:
    name: event-service
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5433/eventdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        spring.json.add.type.headers: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

user-service:
  base-url: http://user-service:8081

resilience4j:
  circuitbreaker:
    instances:
      userClientCB:
        sliding-window-size: 5          # évalue sur les 5 derniers appels
        failure-rate-threshold: 50      # ouvre le circuit si 50%+ d'échecs
        wait-duration-in-open-state: 10s # attend 10s avant de retenter
        permitted-number-of-calls-in-half-open-state: 2
  timelimiter:
    instances:
      userClientCB:
        timeout-duration: 2s            # abandon si user-service répond pas en 2s