server:
  port: 8082

spring:
  application:
    name: event-service
  datasource:
    url: jdbc:postgresql://postgres-event:5432/eventdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: kafka:9092

user-service:
  base-url: http://user-service:8081

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

app:
  init:
    dev-dataset: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      userClientCB:
        sliding-window-size: 5          # évalue sur les 5 derniers appels
        failure-rate-threshold: 50      # ouvre le circuit si 50%+ d'échecs
        wait-duration-in-open-state: 10s # attend 10s avant de retenter
        permitted-number-of-calls-in-half-open-state: 2
  timelimiter:
    instances:
      userClientCB:
        timeout-duration: 2s            # abandon si user-service répond pas en 2s

