name: Container image scan

on:
  push:
    branches: [ main ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub (optional, set DOCKERHUB_USERNAME/DOCKERHUB_TOKEN secrets)
        if: ${{ secrets.DOCKERHUB_USERNAME }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t myapp:${{ github.sha }} ./user-service

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@v1
        with:
          image-ref: myapp:${{ github.sha }}
          format: 'table'
          exit-code: '1'   # --> 1: fail on HIGH vuln (change to 0 to not fail)
          severity: 'CRITICAL,HIGH'
